export const queryKeys = {
  me: ["me"] as const,
  leads: {
    all: ["leads"] as const,
    list: (params?: Record<string, unknown>) => ["leads", "list", params] as const,
    detail: (id: string) => ["leads", "detail", id] as const,
    attachment: (leadId: string, attachmentId: string) =>
      ["leads", "detail", leadId, "attachment", attachmentId] as const,
  },
  kanban: ["kanban"] as const,
  defaultPipeline: ["pipelines", "default"] as const,
  contracts: {
    all: ["contracts"] as const,
    list: (params?: Record<string, unknown>) => ["contracts", "list", params] as const,
    detail: (id: string) => ["contracts", "detail", id] as const,
    templates: ["contracts", "templates"] as const,
    version: (id: string, version: number) => ["contracts", "version", id, version] as const,
    signed: (id: string) => ["contracts", "signed", id] as const,
  },
  legalKanban: ["legal", "kanban"] as const,
  calendar: {
    all: ["calendar"] as const,
    list: (params?: Record<string, unknown>) => ["calendar", "list", params] as const,
    detail: (id: string) => ["calendar", "detail", id] as const,
    byLead: (leadId: string) => ["calendar", "lead", leadId] as const,
  },
  payments: {
    all: ["payments"] as const,
    list: (params?: Record<string, unknown>) => ["payments", "list", params] as const,
    commissions: ["payments", "commissions"] as const,
    rules: ["payments", "rules"] as const,
  },
  dashboard: {
    me: (params?: Record<string, unknown>) => ["dashboard", "me", params] as const,
    admin: (params?: Record<string, unknown>) => ["dashboard", "admin", params] as const,
  },
  reports: (params?: Record<string, unknown>) => ["reports", params] as const,
  users: ["users"] as const,
  userDirectory: ["users", "directory"] as const,
  userDetail: (userId: string) => ["users", "detail", userId] as const,
  userPermissions: (userId: string) => ["users", userId, "permissions"] as const,
  teams: ["teams"] as const,
  teamMembers: (teamId: string) => ["teams", teamId, "members"] as const,
  orgTree: ["teams", "org-tree"] as const,
  leadNames: ["lead-names"] as const,
  plans: ["plans"] as const,
  roles: {
    catalog: ["roles", "catalog"] as const,
    withPermissions: ["roles", "with-permissions"] as const,
  },
  distributionRules: ["distribution", "rules"] as const,
  notifications: ["notifications"] as const,
  search: (q: string) => ["search", q] as const,
};
